{% set version = "0.9" %}

package:
  name: scipilo
  version: {{ version }}

source:
  ../scipilo-0.9.tar.gz

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - scipilo

about:
  license: MIT
  summary: 'zocalo runners for scipion'
  description:  'This module contains zocalo consumers for scipion'
  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst